### PR TITLE
Fix crash on anki v23.10

### LINKED ISSUE #167: Crash on 23.10
**Anki version & Operating System:** 23.10rc3

**When does the crash happens?** Startup

**Traceback:** 

```
Anki 23.10 (ef6f533c) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: Linux-6.5.9-arch2-1-x86_64-with-glibc2.38
Flags: frz=False ao=True sv=3
Add-ons, last update check: 2023-10-31 21:23:01

When loading Life Drain:
Traceback (most recent call last):
  File "/home/mateus/Projects/anki/qt/aqt/addons.py", line 244, in loadAddons
    __import__(addon.dir_name)
  File "/home/mateus/.local/share/Anki2/addons21/lifedrain/__init__.py", line 6, in <module>
    main()
  File "/home/mateus/.local/share/Anki2/addons21/lifedrain/main.py", line 28, in main
    setup_review(lifedrain)
  File "/home/mateus/.local/share/Anki2/addons21/lifedrain/main.py", line 100, in setup_review
    gui_hooks.review_did_undo.append(
AttributeError: module 'aqt.gui_hooks' has no attribute 'review_did_undo'
```

### PR DESCRIPTION
**Pull request by Yutsuten**
Fixes #167

`review_did_undo` hook was removed in v23.10.

[23.10beta6 changelog](https://github.com/ankitects/anki/releases/tag/23.10beta6)

> Remove legacy v1/v2 code by abdnh in https://github.com/ankitects/anki/pull/2727. This may also cause errors in some add-ons if they were referencing hooks that only applied to v1/v2.

### CODE REVIEW

**Comment by Yutsuten** [comment]
Hopefully the ruff fixes won't break things to people. Tested in a Linux environment and working.

**Comment by edr1412** [comment]
Can you upload this version to AnkiWeb? Thanks!

**Comment by Yutsuten** [comment]
Actually, I planned to do that already. But I can't.

See: [Cannot update my own add-on](https://forums.ankiweb.net/t/cannot-update-my-own-add-on/36433)

Edit: Seems that they fixed it. I'll upload soon.

**Comment by edr1412** [comment]
Hi, with v2.7.2 I find an error occurring frequently when I select a deck (after I do some review, and then quit to the main decks view). I also noticed that someone encountered this too, and he left a review on https://ankiweb.net/shared/info/715575551 . And I have the same Debug Info as his.

**Comment by Yutsuten** [comment]
@edr1412 Thanks for reporting the bug.
Just to be sure, could you share your debug info too? I want to see what is common for you two, because I don't see the error.

Also, a more descriptive way to reproduce the bug is welcome. How do you change between screens? Shortcut? Mouse? What are the exact steps so I can make the same here?

**Comment by Yutsuten** [comment]
Oohhh I see, there is a specific flow needed to trigger the bug.

1. Answer the card
2. Press `D` and return to deck selection
3. Press `S` to select a deck and BOOM

Fixing here...

**Pull request merged**
